# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef4cbd34c9b1ab78fd3673807a8ec5f735c996eb4247f3dacb15254fb8da40f0317a77b900e3c0106575bc96aac619323d31e34510af066a5da58bd998449df6

test:
  secret_key_base: 03fbc30b1c3056b5264059c169618ca8a00ffa93677759c29048961d1a4f823c725e0877a75a53551c97ca1c5e17678638bffbb358b720c71c3b8421a1e2bb88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
